[package]
name = "sb_workers"
version = "0.1.0"
authors = ["Supabase <team@supabase.com>"]
edition = "2021"
license = "MIT"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
deno_http.workspace = true
deno_config.workspace = true

http_utils.workspace = true
graph.workspace = true

sb_core.workspace = true
sb_event_worker.workspace = true
sb_fs.workspace = true

anyhow.workspace = true
uuid.workspace = true
tokio.workspace = true
hyper_v014.workspace = true
serde.workspace = true
bytes.workspace = true
log.workspace = true
enum-as-inner.workspace = true
futures-util.workspace = true
tokio-util.workspace = true
thiserror.workspace = true
scopeguard.workspace = true
once_cell.workspace = true
