[package]
name = "cpu_timer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
libc = { workspace = true }
nix = { version = "0.26.2", features = ["signal"] }
tokio = { workspace = true }
log = { workspace = true }
