[package]
name = "sb_core"
version = "0.1.0"
authors = ["Supabase <team@supabase.com>"]
edition = "2021"
resolver = "2"
description = "We'll take care of this later"
license = "MIT"

[lib]
path = "lib.rs"

[dependencies]
deno_net.workspace = true
deno_web.workspace = true
deno_fetch.workspace = true
deno_websocket.workspace = true
anyhow.workspace = true
deno_core.workspace = true
tokio.workspace = true
deno_http.workspace = true
hyper.workspace = true
serde.workspace = true
bytes.workspace = true
supabase_edge_worker_context = { version = "0.1.0", path = "../supa_worker_context" }
